trigger:
- master
pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build
        npm run test
      displayName: 'npm install, build, and test'

    - task: Docker@2
    displayName: Push an image
     inputs:
      azureSubscriptionEndpoint: '$(5a0eee50-4814-4a84-babe-068c6bee0201)'
      azureContainerRegistry: '$(classicpipeline.azurecr.io)'
      imageName: '$(classicpipeline.azurecr.io.image)'
      command: push         